### ISSUE TITLE
Test fails with an error: css selector is not supported for this session

### ISSUE THREAD

**Issue by simmosoonsein** [selenide-examples/selenide-appium#1]
Using the example project out of the box, changing only element selector method:
$(By.cssSelector("id-selector"))
or 
$("#id")
will result with an error:

**Locator Strategy 'css selector' is not supported for this session**

**Comment by asolntsev** [comment]
@simmosoonsein And what do you suggest?
AFAIK we cannot fix it because Appium doesn't support CSS selectors.
