### ISSUE TITLE
Does selenide-appium support iOS predicate locator or Android UIAutomation2 locator?

### ISSUE THREAD

**Issue by ansonliao** [selenide-examples/selenide-appium#26]
Hi,
Could you kindly help to advise the locator short method `$` and `$$` support `iOS predicate` locator stragety and `Android UIAutomation` locator strategy?
I know `Selenide-Appium` support the native Appium locator strategy annotation `@AndroidFindBy` and `@IOSFindBy`, but these 2 annotation without `name` of the element, and Selenide element types support `name` property.

Thanks.

**Comment by asolntsev** [comment]
@ansonliao Can you please bring some example of iOS predicate locator stragety and Android UIAutomation locator strategy? 

I think Selenide-appium supports them, not sure what exactly you mean.

**Comment by ansonliao** [comment]
Hi @asolntsev , 
The very simple case as below.
```
@iOSXCUITFindBy(iOSNsPredicate = "name == 'submit.button'")
@AndroidBy(uiAutomator = "name == 'submit.button")
private WebElement submitButton;
```

If we can replace it by `selenide-appium` similar:
```
private SelenideElement submitButton = $(iosPredicateString("submit.button")).as("Submit Button");
```

Thanks.

**Comment by asolntsev** [comment]
@ansonliao First of all, your initial code just works - if you replace `WebElement` by `SelenideElement`:

```java
@iOSXCUITFindBy(iOSNsPredicate = "name == 'submit.button'")    // or `iOSClassChain = ...`
@AndroidBy(uiAutomator = "new UiSelector().name('submit.button').className('android.widget.Button'))")
private SelenideElement submitButton;
```

But you also can write a similar code without annotations:
```java
import static com.codeborne.selenide.appium.selector.CombinedBy.android;
import static io.appium.java_client.AppiumBy.androidUIAutomator;
import static io.appium.java_client.AppiumBy.iOSNsPredicateString;
import static com.codeborne.selenide.appium.SelenideAppium.$;

SelenideAppiumElement submitButton = $(
  android(androidUIAutomator("new UiSelector...")).ios(iOSNsPredicateString("name == 'submit.button'"))
);
  
submitButton.shouldHave(text("Yes!"));

```

**Comment by ansonliao** [comment]
Oh apology for late reply @asolntsev , thanks for your instructions, you are always the best.

**Comment by ansonliao** [comment]
BTW, I have another stupid question would like to ask help from you @asolntsev , we are running `WebdriverIO` with Appium for my mobile GUI testing, we are investigating whether can migrate to `Selenide-Appium`, now we are manage the selectors in YAML or database, so do you have a some examples of `Selenide` that the selectors stores in the external file?

For my existing example:

home.screen.elements.yml
```
login_button:
  selectors:
    ios: "~login.button"
    android: "login.button"
  name: "The login button"
```


HomeScree.ts:
```
export default class HomeScreen {
  ...
  get loginButton() {
    return $(parseYaml([home.screen.element.yml.login_button.selectors[ios/android]]));
  }
  ...
}
```


Thanks.

**Comment by ansonliao** [comment]
Hi @asolntsev , I follow the instructions of the combined selectors for mobile apps (https://selenide.org/2023/05/29/selenide-6.15.0/#combined-selectors-for-mobile-apps) but failed, I checked all the releasee blog from the site, but didn't mention for this combined selectors updates information, could you kindly help to advise how can I correct my usage?
Thanks.

<img width="1299" alt="image" src="https://github.com/selenide-examples/selenide-appium/assets/6060224/ac671374-ff6c-4d10-83a0-236863011865">

**Comment by asolntsev** [comment]
@ansonliao No, Selenide doesn't have a feature for storing selectors in external files. 
But you don't really need it. Look, this code is simple and readable:
```java
    $(android(accessibilityId("login.button")).
      ios(accessibilityId("~login.button"))
    ).click();
```


P.S. I personally think that storing locators outside of the test is a bad idea. It only brings more complexity to your tests.

**Comment by ansonliao** [comment]
Hi @asolntsev , 
Understood.
And now Selenium introducing `WebDriverListener` and I note that its methods such as `beforeClick(WebElement element)` only support `WebElement` officially, is there any solution to let them to support `SelenideElement` as well?

References:
- https://github.com/SeleniumHQ/selenium/blob/8cebe1082cc07e6aa6873f0054f2ae60d8cc9912/java/src/org/openqa/selenium/support/events/WebDriverListener.java#L125

**Comment by asolntsev** [comment]
@ansonliao But why do you need it?

1. No, `WebDriverListener` is Selenium API, and it doesn't know anything about Selenide classes. It operates only with `WebElement` instances.
2. Technically you can wrap `WebElement` into `SelenideElement` just by calling `$(element)`. But it might cause indefinite loops etc. I would say it's rather a signal that there should be a better solution. it Let's first clarify what problem do you ant to solve?

**Comment by ansonliao** [comment]
Hi @asolntsev , thanks for your reply.
For the `WebDriverListener`, we would like to log some details to the reporting, such as below:
<img width="1410" alt="image" src="https://github.com/selenide-examples/selenide-appium/assets/6060224/3ffd25d4-b4a7-4201-9b16-2bd97cd56fda">

**Comment by asolntsev** [comment]
Now I understand.
No, you don't need `WebDriverListener` in this case.
Instead, you can use `SelenideLogger.addListener(...)`. 

NB! There is already built-in feature `TextReport` in Selenide that can generate such a report for you:
https://selenide.org/documentation/reports.html

P.S. Selenide+Allure adapter also uses this approach:
```java
@BeforeAll
  public static void setUp() {
    SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(true));
  }
```

**Comment by ansonliao** [comment]
Hi @asolntsev ,
All testing report is sent to the `Reportportal` in this report center, we do not expect to check the testing report in the console log, we are running the test scripts in CI/CD

**Comment by asolntsev** [comment]
Then you can create your own listener similar to `AllureSelenide`.

**Comment by ansonliao** [comment]
Yes, now are using `@Listeners({ReportPortalTestNGListener.class})`, for this question is try to log by `WebDriverListener` of Selenium officially

**Comment by ansonliao** [comment]
Dear @asolntsev ,
Apology for troubling you again on the simple question, as Selenide documents are not details in deep.
As checked, for the web GUI testing, `Selenide` has methods to check the execution browser type, such as the method: `com.codeborne.selenide.WebDriverRunner.isChrome()`, 
Could you kindly help to advise are there similar methods for Appium?
Such as `isIos()`, `isAndroid()`, I checked but no found.

Thanks.

**Comment by asolntsev** [comment]
@ansonliao Hi.
I would say Selenide should NOT provide such a method. Methods like `isCrome()` were occasionally made public. :)

Why do you need such a method?
You are the source of this information.  You are telling Selenide which browser/OS to run. Why do you want to ask the same information back?

**Comment by asolntsev** [comment]
@ansonliao And yes, `selenide-appium` provides such methods:
* `com.codeborne.selenide.appium.AppiumDriverRunner#isAndroidDriver`
* `com.codeborne.selenide.appium.AppiumDriverRunner#isIosDriver`

**Comment by ansonliao** [comment]
> @ansonliao Hi. I would say Selenide should NOT provide such a method. Methods like `isCrome()` were occasionally made public. :)
> 
> Why do you need such a method? You are the source of this information. You are telling Selenide which browser/OS to run. Why do you want to ask the same information back?

Hi @asolntsev , 
We meet the case is some screens of the mobile App, the assert screen is loaded by some element, but this expected element is different in iOS and Android, 
For example, 
in iOS we can `$(ios(accessibilityId("A"))).as("A element").shouldBe(visible, ofMillis(5_000))`, 
but in Android, the screen has some minor differences, `$(android(id("B"))).as("B element").shouldBe(visible, ofMillis(5_000))`

Before I try to implement this:
```
SelenideElement checkElement = $(android(id("B")).ios(accessibilityId("A"))).as("Check element");
checkElement.shouldBe(visible, ofMillis(5_000))
```
by this implementation, in the text report or other report, we can't identify what is the `Check element` exactly when failed at this point.

So we try to separate the check element by platform, maybe:
```
Selement checkElement = isIos() ? $(android(id("B")).ios(accessibilityId("A"))).as("Check element") : $(android(id("B"))).as("B element");
checkElement.shouldBe(visible, ofMillis(5_000))
```
then the testing report will display what element is expected to be displayed exactly and trace the failure more easily by QA.

**Comment by asolntsev** [comment]
> trace the failure more easily

Wait, but to trace the failure easily, it's enough to just read the stack trace. It says exactly the line where the failure happened.

Probably it's better to just remove `.as("Check element")` part because it's misleading?

**Comment by asolntsev** [comment]
> developer will check the failure

Do you really think that developers cannot read stacktraces?
Believe me, for develop, the full error message with stack trace is the best information source ever possible. It's definitely better than any tables or hand-written names of elements. These names may be misleading, while the stacktrace always says the truth.

Anyway, there is a solution (but I personally don't find it a good idea): https://github.com/selenide-examples/selenide-appium/issues/26#issuecomment-1911671753

**Comment by ansonliao** [comment]
> > developer will check the failure
> 
> Do you really think that developers cannot read stacktraces? Believe me, for develop, the full error message with stack trace is the best information source ever possible. It's definitely better than any tables or hand-written names of elements. These names may be misleading, while the stacktrace always says the truth.
> 
> Anyway, there is a solution (but I personally don't find it a good idea): [#26 (comment)](https://github.com/selenide-examples/selenide-appium/issues/26#issuecomment-1911671753)

Hi @asolntsev , 
Thanks for your reply.
Definitely developer can read stacktraces, but developer don't want to spend much time on the automation test failure, for example they don't want to trace the failure by open the Java TestNG test class, then open the page object, then open the methods, then Oppos the failure maybe here, then Oppoos, maybe this element don't displays, then...
Developer prefer want the failure more clear for example within 10 seconds, and automation engineer define the Page Object maybe is different from developer's Page Object in their mind (they follow the UX design, for example developer named some popup is `toast` componet, maybe automation engineer align all the popup to "Popup" component).

And yes, https://github.com/selenide-examples/selenide-appium/issues/26#issuecomment-1911671753 works for me, thanks for your all replies.

**Comment by asolntsev** [comment]
@ansonliao Sorry, I don't understand at all. What should happen next? Develop finds that his page object is different, and then what? He will need to open IDE and change the code. He will need to find the right line in the code, using... YES, stacktrace! 

Anyway, if the reason is in different locators for page object element, how can help the alias `.as("Check element")` or `.as("B element")`? It **hides** the locator. It's rather misleading.

**Comment by ansonliao** [comment]
Hi @asolntsev , 
Never mind, different company has the different requires, it's just my case in my company.
